## Installing NumPy

Before we start using NumPy, we need to install it. Open your terminal or command prompy and type:

`pip install numpy`

# Chapter 1

This section demonstrates how to inspect and work with different data types in numpy. The code includes:
1. **Inspecting Python and Numpy Versions**: Using `platform` to get the Python version and `np.__version__` to get the Numpy version.

In [37]:
import platform
import numpy as np

print('Python version: ' + platform.python_version())
print('Numpy version: ' + np.__version__)
import pandas as pd

Python version: 3.9.19
Numpy version: 1.26.4


2. **Creating and Inspecting Arrays with Various Data Types**:
- We create numpy arrays with different types such as `float32`, `complex64`, `bool`, and string types.
- We show how numpy handles fixed-length string types (`S`) and unicode (`U`), where the array will truncate any string that exceeds the specified length.

In [38]:
# Display the common numpy data types along with their type codes
dtypes = pd.DataFrame(
    {
        'Type': ['int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32', 'int64', 'uint64', 'float16', 'float32', 'float64', 'float128', 'complex64', 'complex128', 'bool', 'object', 'string_', 'unicode_'],
        'Type Code': ['i1', 'u1', 'i2', 'u2', 'i4', 'u4', 'i8', 'u8', 'f2', 'f4 or f', 'f8 or d', 'f16 or g', 'c8', 'c16', '', 'O', 'S', 'U']
        }
    )

print(f'Data Types in NumPy:\n {dtypes}')

Data Types in NumPy:
           Type Type Code
0         int8        i1
1        uint8        u1
2        int16        i2
3       uint16        u2
4        int32        i4
5       uint32        u4
6        int64        i8
7       uint64        u8
8      float16        f2
9      float32   f4 or f
10     float64   f8 or d
11    float128  f16 or g
12   complex64        c8
13  complex128       c16
14        bool          
15      object         O
16     string_         S
17    unicode_         U


3. **Displaying Data Types**: We use `dtype` to inspect the data type of each array created.

In [39]:
# Create an array with a specified data type (float32)
arr = np.array([1,2,3], dtype='f4')
print(f'Array: {arr}')
print(f'Data Types of Array:\n {arr.dtype}')

Array: [1. 2. 3.]
Data Types of Array:
 float32


In [40]:
# Create a complex array with complex64 data type
arr = np.array([1+2j, 3-4j], dtype=np.complex64)
print(arr)
print(arr.dtype)

[1.+2.j 3.-4.j]
complex64


In [42]:
# Create an array with a fixed string length ('S3' limits to 3 characters)
s = np.array(['abc', 'defg'], dtype='S3')
print(s)
print(s.dtype)

[b'abc' b'def']
|S3


In [43]:
# Numpy string and unicode data types are fixed-length

# For string_, the array length will be based on the longest string
arr = np.array(['a', 'ab', 'abc'], dtype=np.string_)
print(arr.dtype)
arr = np.array(['a', 'ab', 'abc'], dtype=np.unicode_)
print(arr.dtype)

|S3
<U3


This section demonstrates how to create different types of numpy arrays and perform array operations such as repeating elements, creating identity matrices, extracting diagonals, and filling arrays with specific values.
## 1. **Creating Arrays**:
- `np.array()`: Creates an array from a list.

In [44]:
# Create an array with values from 0 to 9
arr = np.array(range(10))
print(f'Array (with range function): {arr}')

Array (with range function): [0 1 2 3 4 5 6 7 8 9]


In [45]:
# Create a 2D array with specified dtype
arr = np.array([[1,2,3], [4,5,6]], dtype='i2')
print(f'2D Array: \n {arr}')

2D Array: 
 [[1 2 3]
 [4 5 6]]


In [46]:
# Create an array with specified values
arr = np.array([1,2,3,4,5])
print(f'1D Array: {arr}')

1D Array: [1 2 3 4 5]


- `np.arange(start, stop, step)`: Generates values from `start` to `stop` with a specified `step`.

In [47]:
# Generate an array with values from 0 to 20 with step size 2
arr = np.arange(0, 20, 2)
print(f'Array (with step size of 2): \n {arr}')


Array (with step size of 2): 
 [ 0  2  4  6  8 10 12 14 16 18]


- `np.linspace(start, stop, num)`: Generates a specified number of evenly spaced values between `start` and `stop`.

In [48]:
# Generate an array of 20 evenly spaced values from 0 to 10
arr = np.linspace(0, 10, 20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [49]:
# Exclude the endpoint and return the step size
arr, step = np.linspace(0, 10, 20, endpoint=False, retstep=True)
print(arr)
print(step)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]
0.5


- `np.random.rand()`: Generates random numbers from a uniform distribution in [0, 1).

In [50]:
# Generate a random 3x3 array
arr = np.random.rand(3, 3)
print(arr)

[[0.53771794 0.72870454 0.77668242]
 [0.20843758 0.70714531 0.04761214]
 [0.3339304  0.50937999 0.00436451]]


## 2. **Creating Arrays with Specific Values**:
- `np.zeros()`: Creates an array filled with zeros.

In [51]:
# Create a 2x3 array of zeros with dtype 'i4'
zeros = np.zeros((2,3), dtype='i4')
print(zeros)

[[0 0 0]
 [0 0 0]]


In [52]:
# Create a zero array with the same shape as `arr`
zeros = np.zeros_like(arr)
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


- `np.ones()`: Creates an array filled with ones.

In [53]:
# Create a 2x3 array of ones
ones = np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [54]:
# Create a ones array with the same shape as `arr`
ones = np.ones_like(arr)
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


- `np.empty()`: Creates an uninitialized array.

In [55]:
# Create an uninitialized array
empty = np.empty((2,3))
print(empty)

[[1. 1. 1.]
 [1. 1. 1.]]


In [56]:
# Create an empty array with the same shape as `arr`
empty = np.empty_like(arr)
print(empty)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


- `np.full()`: Creates an array filled with a specified value.

In [57]:
# Create a 2x3 array filled with 5
p = np.full((2,3), 5)
print(p)

[[5 5 5]
 [5 5 5]]


In [58]:
# Create an array with the same shape as `arr` filled with 5
p = np.full_like(arr, 5)
print(p)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


## 3. **Repeating and Tiling Arrays**:
- `np.repeat()`: Repeats elements of an array.

In [59]:
# Repeat each element of the array by 3 times
arr = [0, 1, 2]
print(np.repeat(arr, 3)) # or np.repeat(range(3), 3)

[0 0 0 1 1 1 2 2 2]


In [60]:
# Repeat elements along a specified axis
arr = [[1,2], [3,4]]
print(np.repeat(arr, [1,2], axis=0))

[[1 2]
 [3 4]
 [3 4]]


- `np.tile()`: Tiling an array by repeating it along specified axes.

In [61]:
# Repeat the array 3 times
arr = [0, 1, 2]
print(np.tile(arr, 3))

[0 1 2 0 1 2 0 1 2]


In [62]:
# Tile the array along two axes
print(np.tile(arr, (2,2)))

[[0 1 2 0 1 2]
 [0 1 2 0 1 2]]


## 4. **Identity Matrix**:
- `np.eye()`: Creates an identity matrix.

In [63]:
# Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [64]:
# Create a 5x5 identity matrix with the diagonal shifted upwards
identity_matrix = np.eye(5, k=1)
print(identity_matrix)

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


In [65]:
# Create a 5x5 identity matrix with the diagonal shifted downwards
identity_matrix = np.eye(5, k=-2)
print(identity_matrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


## 5. **Diagonal Operations**:
- `np.diag()`: Extracts the diagonal of an array or creates a matrix with a specified diagonal.

In [66]:
# Generate a random 5x5 array
arr = np.random.rand(5,5)
print(arr)

[[0.5025735  0.93647436 0.38616034 0.48787744 0.29147913]
 [0.94238108 0.67411119 0.9751561  0.39942163 0.34575771]
 [0.87480223 0.19855456 0.99302143 0.17197138 0.62613897]
 [0.81278327 0.83744734 0.97473187 0.0094469  0.83830695]
 [0.94979677 0.18287751 0.86575536 0.15151808 0.30903507]]


In [67]:
# Extract the diagonal of the array
print(np.diag(arr))

[0.5025735  0.67411119 0.99302143 0.0094469  0.30903507]


In [68]:
# Create a matrix with the specified diagonal
arr = np.diag([1,2,3,4,5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
