## Importing NumPy

In [1]:
import numpy as np

This code demonstrates various ways to slice, index, and filter numpy arrays using different techniques.
1. **Basic Indexing and Slicing**:
- `arr[5][5]` vs `arr[5,5]`: Indexing an element at row 5, column 5. The latter is more concise.
- `arr[1:3, 4:6]`: Slice the array from rows 1 to 2 and columns 4 to 5.

In [2]:
arr = np.array(range(100)).reshape((10,10))

# Indexing an element (alternative ways)
print(arr[5][5]) # Traditional way
print(arr[5,5]) # More concise

# Slicing the array
print(arr[1:3, 4:6])

55
55
[[14 15]
 [24 25]]


2. **Ellipsis (`...`) Slicing**:
- `arr[0, ...]`: This shorthand allows you to select the first slice along the first axis while leaving the other dimensions automatically filled.

In [3]:
# Ellipsis slicing: auto-complete the dimensions
arr = np.array(range(16)).reshape(2,2,2,2)

# Equivalent to arr[0,:,:,:]
print(arr[0, ...])

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


3. **Setting Values with Slicing**:
- `arr[1:3, :] = 100`: Assigns the value 100 to the rows 1 and 2 in all columns.
- `arr[:, 8:] = 100`: Assigns the value 100 to all rows, starting from column 8 to the end.

In [4]:
# Modify elements using slicing
arr[1:3,:] = 100 # Assign 100 to rows 1 and 2
arr[:,8:] = 100 # Assign 100 to all rows starting from column 8
print(arr)

[[[[  0   1]
   [  2   3]]

  [[  4   5]
   [  6   7]]]


 [[[100 100]
   [100 100]]

  [[100 100]
   [100 100]]]]


4. **Boolean Indexing**:
- `arr1[bools]`: Uses a boolean array to filter the elements in `arr1`.
- `arr1[~bools]`: Negates the boolean condition.
- `arr1[(arr2 < 2) | (arr2 > 4)]`: Applies multiple conditions to filter the elements.

In [5]:
# Boolean indexing
arr1 = np.arange(25).reshape((5,5))
bools = np.array([True, True, False, True, False])
print(arr1[bools]) # Select elements where bools is True

# Negate the boolean condition
print(arr1[~bools]) # Select elements where bools is False

# Multiple conditions for filtering
arr2 = np.array([1,2,3,4,5])
print(arr1[(arr2<2) | (arr2>4)]) # Elements where arr2 is less than 2 or greater than 4

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [15 16 17 18 19]]
[[10 11 12 13 14]
 [20 21 22 23 24]]
[[ 0  1  2  3  4]
 [20 21 22 23 24]]


5. **Fancy Indexing**:
- `arr[[3,1,2], [3,2,1]]`: Selects specific elements using lists of indices for rows and columns.
- `arr[[3,1,2]][:, [6,4,8]]`: Selects specific rows and columns using fancy indexing.

In [6]:
# Fancy indexing with row and column selections
arr = np.random.rand(10,10)
print(arr[[3,1,2], [3,2,1]]) # Select arr[3,3], arr[1,2], arr[2,1]

# Select rows and columns using fancy indexing
print(arr[[3,1,2]][:, [6,4,8]]) # Select rows 3,1,2 and columns 6,4,8

[0.79902178 0.62122163 0.5504172 ]
[[0.09080096 0.14884854 0.40579676]
 [0.47608016 0.63486576 0.86147349]
 [0.83954308 0.54939029 0.60408969]]


6. **Negative Indexing**:
- Using negative values like `-1` to infer dimensions, such as `arr.reshape(4, -1)` to automatically infer the number of columns.

In [7]:
# Using negative numbers for automatic dimension inference
arr = np.array(range(16)).reshape((4,-1))
print(arr.shape) # Automatically infers the number of columns

(4, 4)


7. **Conditional Selection**:
- `arr[arr > 5]`: Selects the elements greater than 5 in the flattened array.
- `np.where(condition, true_return, false_return)`: Returns elements based on a condition (e.g., `-1` if the condition is true, `10` otherwise).

In [8]:
# Finding elements greater than 5 using boolean indexing
arr = np.arange(16).reshape(4,4)
print(arr[arr > 5]) # Select elements greater than 5 (flattened array)

# Using np.where for conditional selection
print(np.where(arr > 5, -1, 10)) # -1 where condition is True, else 10

[ 6  7  8  9 10 11 12 13 14 15]
[[10 10 10 10]
 [10 10 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


8. **Finding Indices**:
- `np.argwhere(arr > 5)`: Returns the indices of elements that satisfy the condition.

In [9]:
# Find the indices of elements that satisfy a condition
print(np.argwhere(arr > 5)) # Indices where elements are greater than 5

[[1 2]
 [1 3]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [3 0]
 [3 1]
 [3 2]
 [3 3]]
