In [1]:
import numpy as np

# Create a new random array
arr = np.random.rand(3,4)

This code demonstrates how to sort a numpy array along different axes, both in-place and with copies, as well as how to retrieve the indices of sorted elements.
## 6.1. **Sorting Along Rows (axis=0)**:
- `np.sort(arr, axis=0)`: Sorts the array along the rows, returning a new array (copy).

In [2]:
# Sort along the row and return a copy
print(np.sort(arr, axis=0))

# Sort along the row in place
arr.sort(axis=0)
print(arr)

[[0.1072139  0.43345691 0.36320244 0.04739047]
 [0.31877436 0.5501819  0.4245276  0.08920689]
 [0.74455195 0.78257843 0.60116779 0.25956484]]
[[0.1072139  0.43345691 0.36320244 0.04739047]
 [0.31877436 0.5501819  0.4245276  0.08920689]
 [0.74455195 0.78257843 0.60116779 0.25956484]]


- `arr.sort(axis=0)`: Sorts the array along the rows **in-place**, modifying the original array.

In [3]:
# Sort along the row in place
arr.sort(axis=0)
print(arr)

[[0.1072139  0.43345691 0.36320244 0.04739047]
 [0.31877436 0.5501819  0.4245276  0.08920689]
 [0.74455195 0.78257843 0.60116779 0.25956484]]


## 6.2. **Sorting Along Columns (axis=1)**:
- `np.sort(arr, axis=1)`: Sorts the array along the columns, returning a new array (copy).

In [4]:
# Sort along the column and return a copy
print(np.sort(arr, axis=1))

[[0.04739047 0.1072139  0.36320244 0.43345691]
 [0.08920689 0.31877436 0.4245276  0.5501819 ]
 [0.25956484 0.60116779 0.74455195 0.78257843]]


- `arr.sort(axis=1)`: Sorts the array along the columns **in-place**, modifying the original array.

In [5]:
# Sort along the column in place
arr.sort(axis=1)
print(arr)

[[0.04739047 0.1072139  0.36320244 0.43345691]
 [0.08920689 0.31877436 0.4245276  0.5501819 ]
 [0.25956484 0.60116779 0.74455195 0.78257843]]


## 6.3. **Getting Sorted Indices**:
- `np.argsort(arr, axis=0)`: Returns the indices that would sort the array along the rows.

In [6]:
# Get the indices that would sort the array along the row
print(np.argsort(arr, axis=0))

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]]


- `np.argsort(arr, axis=1)`: Returns the indices that would sort the array along the columns.

In [7]:
# Get the indices that would sort the array along the column
print(np.argsort(arr, axis=1))

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


- `np.argsort(arr, axis=None)`: Returns the indices of the flattened array (the entire array).

In [8]:


# If axis=None, return the indices of a flattened array
print(np.argsort(arr, axis=None))

[ 0  4  1  8  5  2  6  3  7  9 10 11]
