## Installing NumPy

Before we start using NumPy, we need to install it. Open your terminal or command prompy and type:

`pip install numpy`

## Importing NumPy

In [1]:
import numpy as np

## Creating Arrays

### From Python List

In [4]:
my_py_list = [1, 2, 3, 4, 5, 6]
my_num_array = np.array(my_py_list)
print(type(my_py_list))
print(type(my_num_array))

<class 'list'>
<class 'numpy.ndarray'>


### Using In-Built Function

In [6]:
zeros_array = np.zeros(5)
ones_array = np.ones((4,3))
random_array = np.random.rand(4,4)

print(zeros_array)
print(ones_array)
print(random_array)

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.79895813 0.13943026 0.06659955 0.57229471]
 [0.87950656 0.64733756 0.73135505 0.48874757]
 [0.26990273 0.02474814 0.59542717 0.34587861]
 [0.11031715 0.28292491 0.32830491 0.80634539]]


## Array Attributes

NumPy array has various attributes that provides information about Array's shape, data types, etc...

In [12]:
print(random_array.shape) # Shape of the array
print(random_array.dtype) # Data type of the elements 
print(random_array.ndim) # Numver of dimention
print(random_array.size) # Total number of elements

(4, 4)
float64
2
16


## Indexing and Slicing

You can access the element of an array using indexing, just like with python list

In [20]:
print(random_array[0]) # Access the first element

print(random_array[1:3]) # Access element from 1 to 2

print(random_array[1][3]) # Acess element from row 2 column 4

[0.79895813 0.13943026 0.06659955 0.57229471]
[[0.87950656 0.64733756 0.73135505 0.48874757]
 [0.26990273 0.02474814 0.59542717 0.34587861]]
0.4887475665325587


## Array Operations

NumPy allows for element-wise operations and mathematical operations on arrays.

In [22]:
array_1 = np.array([1, 2, 3])
array_2 = np.array([4, 5, 6])

In [23]:
# Element wise addition
element_addition = array_1 + array_2
element_addition

array([5, 7, 9])

In [24]:
# Element wise multiplication
element_multiplication = array_1 * array_2
element_multiplication

array([ 4, 10, 18])

In [26]:
# Mathematical Function
arr_sin = np.sin(array_1)
arr_sin

array([0.84147098, 0.90929743, 0.14112001])

## Array Broadcasting

Broadcasting allows operations between arrays of different shapes.

In [29]:
new_array = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 2

# Broadcasting all elements to scalar
array_broadcasting = new_array * scalar
array_broadcasting

array([[ 2,  4,  6],
       [ 8, 10, 12]])

## Array Manipulation

You can reshape, transpose, and concatenate arrays.

In [34]:
# Reshape array
reshaped = new_array.reshape(3,2)
reshaped

array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
# Transpose Array
transposed = new_array.T
transposed

array([[1, 4],
       [2, 5],
       [3, 6]])

In [38]:
# Concatenate Arrays
concatenated = np.concatenate((transposed, reshaped))
concatenated

array([[1, 4],
       [2, 5],
       [3, 6],
       [1, 2],
       [3, 4],
       [5, 6]])